### ISSUE TITLE
MudScrollbar does not work on Firefox

### ISSUE THREAD

**Issue by Conbag93** [CodeBeamOrg/CodeBeam.MudExtensions#104]
I use Firefox, and when I visit https://codebeam-mudextensions.pages.dev/mudscrollbar - I cannot take advantage of any of the features there.
I always get a boring "default" scrollbar.

If this could be implemented in Firefox somehow, that would be great.
Alternatively, if this is a known limitation - I suggest documenting this somewhere on the demos page.

P.s. - thanks for your work, this is a great addition to the already fantastic MudBlazor.

**Comment by mckaragoz** [comment]
Unfortunately, Firefox has a little customization support on their scrollbar. They don't have webkit variables. We defined the situation in parameter descriptions, the parameters doesn't work for Firefox. You can customize it only with `FirefoxStyle` parameter on MudScrollbar.

**Comment by mckaragoz** [comment]
If you have further questions or noticed more flexible scrollbar options on Firefox, please reopen this issue.
