### ISSUE TITLE
MudSelectExtended: Bug With Virtualize and SelectedItems Style

### ISSUE THREAD

**Issue by antonKrizmanic** [CodeBeamOrg/CodeBeam.MudExtensions#109]
Hy, I'm using MudSelectExtended component with `record SelectItem` and MultiSelection set to `true`. After selecting two or more option closing select and reopening select only the last selected item is marked as selected. Is this bug or I'm doing something wrong?

```csharp
<MudSelectExtended
        T="SelectItem"
        MultiSelection="true"
        MultiSelectionTextFunc="@(new Func<List<SelectItem>, string>(GetMultiSelectionText))"
        ToStringFunc="@(item => item.Text)"
        Label="Multi select"
        @bind-SelectedValues="BoundItems"
        ItemCollection="Items"
        SearchBox="true"
        Virtualize="true"
        Clearable
        AnchorOrigin="Origin.BottomCenter"
        Variant="Variant.Outlined"/>

@code {

        private ICollection<SelectItem> Items = new List<SelectItem>()
        {
                new(1, "Item 1"),
                new(2, "Item 2"),
                new(3, "Item 3"),
                new(4, "Item 4"),
                new(5, "Item 5"),
                new(6, "Item 6"),
        };

        public IEnumerable<SelectItem> BoundItems { get; set; }


        private string GetMultiSelectionText(List<SelectItem> selectedValues)
        {
                return $"{string.Join(", ", selectedValues.Select(x => x.Text))}";
        }

        public record SelectItem(int Id, string Text);
}
```

**Comment by mckaragoz** [comment]
It look like a Virtualization problem. If you set `Virtualize="false"` it look like work.

Actually i have no idea why this isn't working for now, we just implement the blazor virtualize component. We need to look deeper about virtualize, if you have any idea about this please prepare a PR.

**Comment by antonKrizmanic** [comment]
Thanks for reply and for providing workaround for now. At the moment I don't have any idea how to fix this, since I didn't use blazor virtualize on my own.
Workaround isn't great, but it's good for situation when there is no too much items.

**Comment by mightyvoodoo** [comment]
+1

Btw, checked Virtualize with core MudSelect with Multiple param, and everything works.
I've tried to do some kind of triage with source, but till now I had no idea about that bug too.
Imo, that's not necessary a problem of Virtualize component, but this can be mistaken.

I think have virtualize working on it's component is most crucial part.

@mckaragoz Any idea? 😃

**Comment by mckaragoz** [comment]
> Btw, checked Virtualize with core MudSelect with Multiple param, and everything works.

MudSelect has virtualize?

**Comment by mightyvoodoo** [comment]
> MudSelect has virtualize?

It's via ChildContent.

**Comment by mightyvoodoo** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0#state-changes-2

Maybe this is related?

**Comment by mckaragoz** [comment]
> > MudSelect has virtualize?
> 
> It's via ChildContent.

Understand i didn't try with the MudSelect via render fragment, did you try same with extended with render fragment also?

Item highlight is controlled by UpdateSelectedStyles method.

**Comment by mightyvoodoo** [comment]
I did, and neither `<Virtualize>` nor `<MudVirtualize>` ain't work.
I saw implementation of `UpdateSelectedStyles` and think that bug somewhere here with changing state on select or open.
Component classes are heavy and seems without your guidance there no go.

**Comment by mckaragoz** [comment]
Yeah, writing these codes was very hard for me, because too many rendering process start over and over and i also can't follow them for now. I saw the virtualize problem at the end of the PR but still no idea where is the problem.

**Comment by mightyvoodoo** [comment]
```razor
Selected: @string.Join(", ", selected)
<MudDivider Class="my-5" />
<MudButton OnClick="e => { open = !open; }">Toggle</MudButton>
<MudButton OnClick="e => { list?.ForceUpdate(); }">Force Update</MudButton>

<div style="display: @(open ? "block" : "none");">
    @* Place MudListExtended here instead of MudPopover. *@
    @* Here we don't' need to ForceUpdate() when opened. *@
</div>
<MudPopover @bind-Open="open" AnchorOrigin="Origin.BottomLeft" MaxHeight="240" Class="overflow-y-auto">
    @* Here we need to ForceUpdate() when opened. *@

    <MudListExtended @ref="list" @bind-SelectedValues="selected"
                     ItemCollection="items"
                     MultiSelection="true" Clickable="true" SearchBox="true"
                     Virtualize="true" />
</MudPopover>

@code {
    bool open;
    MudListExtended<string>? list;
    List<string> items = new();
    IEnumerable<string> selected = Enumerable.Empty<string>();

    protected override void OnInitialized()
    {
        for (int i = 0; i != 1000; i++)
        {
            items.Add($"Item {i}");
        }
    }
}
```

I think that it's something related with component render events.

**Comment by mckaragoz** [comment]
@antonKrizmanic this is a workaround for you:

```
<MudSelectExtended
        T="SelectItem"
        @ref="_select"
        MultiSelection="true"
        MultiSelectionTextFunc="@(new Func<List<SelectItem>, string>(GetMultiSelectionText))"
        ToStringFunc="@(item => item?.Text)"
        Label="Multi select"
        @bind-SelectedValues="BoundItems"
        ItemCollection="Items"
        SearchBox="true"
        Virtualize="true"
        Clearable
        AnchorOrigin="Origin.BottomCenter"
        Variant="Variant.Outlined"
        OnOpen="OnOpen"/>

@code {
    MudSelectExtended<SelectItem> _select;
    private ICollection<SelectItem> Items = new List<SelectItem>()
        {
                new(1, "Item 1"),
                new(2, "Item 2"),
                new(3, "Item 3"),
                new(4, "Item 4"),
                new(5, "Item 5"),
                new(6, "Item 6"),
        };

    public IEnumerable<SelectItem> BoundItems { get; set; }

    private async Task OnOpen()
    {
        await Task.Delay(100);
        await _select.ForceUpdate();
    }


        private string GetMultiSelectionText(List<SelectItem> selectedValues)
        {
                return $"{string.Join(", ", selectedValues.Select(x => x.Text))}";
        }

        public record SelectItem(int Id, string Text);
}
```

**Comment by mckaragoz** [comment]
@mightyvoodoo if we add `UpdateSelectedStyles` at the end of the OnAfterRenderAsync, the visual works clearly, but it causes to infinite render loop at some situations.

I fixed the virtualize scroll bug by adding UpdateSelectedStyles to onscroll. But it still have bug if you press arrow keys to select previous next item.

**Comment by radderz** [comment]
Check out my PR #240, I have fixed a few issues to do with selection and virtualisation in it.

**Comment by mckaragoz** [comment]
The main issue looks fixed. If you have another issue relates to this, please re-open this issue or open new issue.
