### ISSUE TITLE
MudSelectExtended margin differs from MudSelect

### ISSUE THREAD

**Issue by BenWhite27** [CodeBeamOrg/CodeBeam.MudExtensions#111]
!!! First off, awesome extensions, my thanks to you for your time and effort !!!!

It seems that one of the internal components of MudSelectExtended receives an `ms-4` class which causes the text value to be presented with an indent.

When compared to the MudBlazor's standard MudSelect control, it doesn't have the margin.

MudSelect
![image](https://user-images.githubusercontent.com/7678016/218320367-3102e865-0c29-4ad1-9205-3b1755b8d2c8.png)

MudSelectExtended
![image](https://user-images.githubusercontent.com/7678016/218320402-a5237cdc-feb3-4d6a-abfe-5d1e3517a9ab.png)

Perhaps it's being added by this line? https://github.com/CodeBeamOrg/CodeBeam.MudExtensions/blob/218c4a8c448c8fdb8c3fd6a91fec7288cba92ff9/CodeBeam.MudExtensions/Components/InputExtended/MudInputCssHelperExtended.cs#L32

**Comment by mckaragoz** [comment]
Absolutely, and already fixed with #108. Will come with the next release. Thanks for feedback :)

**Comment by mckaragoz** [comment]
This ms-4 class need for MudTextFieldExtended, so i didn't notice it breaks the select. My bad. Now fixed that it only applies to textfield.

**Comment by mckaragoz** [comment]
v 6.2.4 is released and should fix the issue. If you have another problem please re-open it or open a new issue.
