### ISSUE TITLE
Problems with CodeInput on small screens

### ISSUE THREAD

**Issue by CaptainJackDE** [CodeBeamOrg/CodeBeam.MudExtensions#115]
With small displays or with many fields the CodeInput does not break and has either an overflow or is cut off by the screen border.

Here is an "exaggerated example" from demo-page:
![image](https://user-images.githubusercontent.com/28738283/218978951-3ad0b83d-66fa-43e6-9171-272111cb865a.png)

**Comment by mckaragoz** [comment]
First of all, CodeInput currently supports max to 12 character. I see your example has count of 22 but you can see there are only 12 boxes.

And for your issue you can add `Class="flex-wrap` to your CodeInput, you can make CSS changes easily for this component.

**Comment by mckaragoz** [comment]
If you have further questions, please reopen this issue.
