### ISSUE TITLE
MudSelectExtended: show selected values as closeable chips

### ISSUE THREAD

**Issue by gle4711** [CodeBeamOrg/CodeBeam.MudExtensions#119]
Hello

it is not an issue, but more a wish. Is it possible to display the selected values as "closable chips" instead of just "chips"? That would be great. I could then simply remove some elements from a selected list by closing the chip.

Greetings 
Erich

**Comment by mckaragoz** [comment]
Good idea, while i handle this, also added that chips can be multilined, can change variant and size also. Will come with the next release.

https://user-images.githubusercontent.com/78308169/219787590-f9e25af4-0ee3-4cbb-8960-90b3511bf111.mp4

Note: Multiline vertical space (row-gap) a little bit less, changed after the video.

**Comment by gle4711** [comment]
Thanks. Looks great.
