### ISSUE TITLE
MudSelectExtended: Searchbox position not fixed, it moves when scrolling

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#120]
The searchbox position of MudSelectExtended is not fixed, it moves when scrolling.
For complete awesomeness I'd like the searchbox to stay where it is.

![123](https://user-images.githubusercontent.com/10358198/219695790-1bd9d176-49ab-4481-b8d4-2cf40113d746.gif)

**Comment by mckaragoz** [comment]
Isn't it by design, it moves up a bit upper to increase space for list items 🙂

**Comment by Yomodo** [comment]
It doesn't really add that much space to justify the searchbox movement, I believe.
I tried adding some sticky CSS, to no avail.

**Comment by mckaragoz** [comment]
Fixed this issue, coming with next release
