### ISSUE TITLE
MudTransferList - MultiSelection - some checks look unchecked, but are checked

### ISSUE THREAD

**Issue by TDroogers** [CodeBeamOrg/CodeBeam.MudExtensions#130]
Hi, I like the new component, however with MultiSelection not all checks show correct when swapping. See the gif.

![2023-02-22_18h06_09](https://user-images.githubusercontent.com/34547552/220703133-236d87c3-21ce-4e50-ad04-66e68f8b0f85.gif)

**Comment by mckaragoz** [comment]
Yeah i also noticed it when i release, on first commit i fixed the visual bug, but it seems to break somewhere again.

And is it only happened when transfering to end list? I see in your video that transfering to start list looks good.

**Comment by TDroogers** [comment]
Yes, its seems to be when transferring to end list.

**Comment by mckaragoz** [comment]
> Yes, its seems to be when transferring to end list.

Merged a PR and probably fix this, will come with the next release, thanks for pointing and debugging this.
