### ISSUE TITLE
Splitter defines StyleBar twice?

### ISSUE THREAD

**Issue by henon** [CodeBeamOrg/CodeBeam.MudExtensions#138]
In MudSplitter.razor I see `@(StyleBar)` at the end of this line:
https://github.com/CodeBeamOrg/CodeBeam.MudExtensions/blob/3b580fa9d21f5f914104fc971842a33507f2dbeb/CodeBeam.MudExtensions/Components/Splitter/MudSplitter.razor#L21

and then two lines later it is defined again in the same class. I guess this is an oversight?

Happens two times in the same file.

**Comment by mckaragoz** [comment]
Yeah, it look like as you said and have no idea why we have the both same, thanks 🙂
