### ISSUE TITLE
DataGrid new component 

### ISSUE THREAD

**Issue by franklupo** [CodeBeamOrg/CodeBeam.MudExtensions#141]
Create a new component data grid
Best regards

**Comment by Yomodo** [comment]
Makes more sense to wait for the official MudBlazor version?

**Comment by mckaragoz** [comment]
Mud Core both have MudTable and MudDataGrid, does your offer has different aspects? An extension should significantly enhance the current components or make a unique one.

**Comment by franklupo** [comment]
DataGrid is a LOB component which should have powerful features like DevExpress or SyncFusion.
The Mud Core doesn't want to on this implementation.

Best regards

**Comment by mkalinski93** [comment]
I agree with @franklupo. It´s a great component in its current state, but lacks many LOB features. Maybe the core DataGrid can be removed and this DataGrid can be referenced. I believe a lot of people are waiting for LOB components to be honest.

**Comment by franklupo** [comment]
LOB components are now required for business applications. Right now using both fantastic MudBlazor and this library, it's hard to create certain types of solutions.
Eg TreeGrid does not exist and is needed

I understand that most developers will be satisfied with the current one but for me it is not like that. I have a DevExpress subscription and use it.
In OpenSource projects I want to use MudBlazor to release code but sometimes it's really frustrating not having features or waiting for bug fixes (from December https://github.com/MudBlazor/MudBlazor/pull/5999).

I understand the difficulties of OpenSource because I also create OpenSource.

best regards
