### ISSUE TITLE
SelectExtended: SearchBox improvements

### ISSUE THREAD

**Issue by mightyvoodoo** [CodeBeamOrg/CodeBeam.MudExtensions#142]
Hello there!

That would be nice if we could:

- Pass Func that allows to customize search logic
- Pass string placeholder for inner input

_p.s.: Thanks for that nice package and all of your work 👍_

**Comment by mckaragoz** [comment]
Fastest merged PR ever 🙂 Hope this is what you want about func and placeholder.


https://user-images.githubusercontent.com/78308169/221415263-053e9e30-78f2-4728-8604-fe2ac82ce347.mp4

And more good news, today we will release the feature with new version.

**Comment by mightyvoodoo** [comment]
@mckaragoz Just awesome, everything that was needed 💪

**Comment by mckaragoz** [comment]
v 6.3.0 is released. Please don't forget about breaking change, you should change script to min.js
