### ISSUE TITLE
DateWheelPicker in Mudpopup

### ISSUE THREAD

**Issue by gle4711** [CodeBeamOrg/CodeBeam.MudExtensions#152]
Hi,
it.s me again. I have another problem with the Datewheelpicker. I want to display the control in a popup. But the control opens behind the popup. I suspect this has something to do with the z-index. I have not been able to get it to work. What do I have to do?

[DateWheelPickerInPopup.txt](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/files/10891787/DateWheelPickerInPopup.txt)

**Comment by mckaragoz** [comment]
Hi,

There is missing parameter here, with new release i will add `PopoverClass` into DateWheelPicker.

When this add, you can do this:

```
<DateWheelPicker PopoverClass="my-popover"

<style>
            .my-popover.mud-popover{
                z-index: 3000 !important;
            }
        </style>
```

Popup's z-index is 2000, so more than 2000 will work.

**Comment by gle4711** [comment]
Thankyou.
