### ISSUE TITLE
MudSelectExtended - Unable to select whole search text using CTRL+A

### ISSUE THREAD

**Issue by Kricz** [CodeBeamOrg/CodeBeam.MudExtensions#156]
When using MudSelectExtended with search enabled, you cannot use CTRL+A to select all text in the search box, making it kinda hard to clear the text of the search field. 
You either have to press backspace multiple times (or keep it pressed) or manually select the whole search text with the mouse manually before being able to clear it with a single backspace.

See https://codebeam-mudextensions.pages.dev/mudselectextended with enabled search for an example.

Expected behavior:
Pressing CTRL+A should select the whole text of the search box if it is being focused.
An additional option (like SearchClearable) to show a small clear button inside of the search box could be a nice addition too.

**Comment by mckaragoz** [comment]
There was a conflict dues to KeyInterceptor. I added a Ctrl + A behavior manually. Also added a parameter that now users can set searchbox clearable.
