### ISSUE TITLE
SelectListExtended - Initially selected item not rendered when using ValuePresenter.ItemContent

### ISSUE THREAD

**Issue by Kricz** [CodeBeamOrg/CodeBeam.MudExtensions#159]
Hi again,

when setting ValuePresenter to ValuePresenter.ItemContent and binding the selected value to a property initialized with a value, the ItemTemplate is not rendered for the selected item. After selecting an item manually, everything seems to work fine.

To following code produces the error:
```razor
<MudSelectExtended ItemCollection="Keys" 
    ValuePresenter="MudExtensions.Enums.ValuePresenter.ItemContent" 
    @bind-Value="SelectedKey"
    Label="Select item">

    <ItemTemplate>
        @{
            var item = MyDtoDict[context.Value];
        }
        <MudText Color="Color.Info">@item.DisplayName</MudText>
    </ItemTemplate>


</MudSelectExtended>

@code{

    static Dictionary<int, MyDto> MyDtoDict = 
        Enumerable.Range(1, 20)
        .Select(i => new MyDto(i, $"Item {i}"))
        .ToDictionary(x => x.Id);

    static ICollection<int> Keys => MyDtoDict.Keys.ToList();

    int SelectedKey {get;set;} = 2;

    record MyDto(int Id, string DisplayName);
}
```

Result:
![image](https://user-images.githubusercontent.com/6401949/224358267-0a54a7c6-5965-4ea9-ba44-e8a631c4cee8.png)

As `SelectedKey` is set to 2, the select box should show the blue colored text `Item 2`.
When opening the select list, the item is also marked as the selected item.

**Comment by mckaragoz** [comment]
Already find a solution, but the solution causes other problems.
