### ISSUE TITLE
MudStepper running CheckChange method twice per step

### ISSUE THREAD

**Issue by PlayerModu** [CodeBeamOrg/CodeBeam.MudExtensions#168]
Debugging through the mudstepper, the CheckChange() method looks to be called twice per step. Is there a reason for this? This is currently causing issues when I submit the data on the final step as it's submitting said data twice. I mat be able to work-around it but just wanted to flag this behavior up as a potential issue.

**Comment by mckaragoz** [comment]
Yes, this is definitely a bug. Thanks for feedback. Could you have a quick look at the solution PR?

**Comment by PlayerModu** [comment]
Thanks for getting a solution prepared so quickly! I think your PR should resolve the issue from what I can see
