### ISSUE TITLE
MudPasswordField Error with recent MudBlazor Update 6.2.1

### ISSUE THREAD

**Issue by derekwelton** [CodeBeamOrg/CodeBeam.MudExtensions#177]
After updating to Mudblazor 6.2.1, the password field is throwing an issue due to the "OnBlurred" event.
![image](https://user-images.githubusercontent.com/31353783/231590493-ad16ad07-a8b7-4008-a742-394fa365f520.png)

**Comment by neozhu** [comment]
me too！

**Comment by mckaragoz** [comment]
This was a change in Mud core library. Already fixed, will come with next release and support MudBlazor 6.2.1 and after

**Comment by franklupo** [comment]
when do you release the new version?

best regards

**Comment by mckaragoz** [comment]
Probably today, but certainly in this week

**Comment by mckaragoz** [comment]
6.4.9 is released and fixed the compatibility problems within MudPasswordField after MudBlazor v. 6.2.1 and after.
