### ISSUE TITLE
Updating to version 6.4.8, breaks the build with emscripten

### ISSUE THREAD

**Issue by jan-johansson-mr** [CodeBeamOrg/CodeBeam.MudExtensions#179]
Hello,

I've isolated a breaking building behavior with MudBlazor extensions, upgrading from 6.4.7 to 6.4.8, where the wasm-tools gives the following message

	cache : warning : Accessing the Emscripten cache at "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.30.Cache.win-x64\8.0.0-preview.3.23172.2\tools\emscripten\cache" (for "sanity") is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.30.Cache.win-x64\8.0.0-preview.3.23172.2\tools\emscripten\cache\cache.lock" and try again. If this occurs deterministically, consider filing a bug.

(Actually, the warning is misleading, since there is no lock file in play, something else is going on here).
(Another note, to be clear, the solution can not be built at all, with the behavior - the build pipeline simply "freezes").

It is exactly when I update, in isolation, codebeam mudblazor extensions, that this behavior kicks in, in my solution.

All other packages are up to date, MudBlazor too (version 6.2.1).

I've downgraded to version 6.4.7, and my tool chain works fine (again).

Thanks,
//Jan

**Comment by mckaragoz** [comment]
Thats probably with MudQrCode component, we add some dependencies for it. We seperate the component into another nuget with the next release, thanks for the feedback.

**Comment by jan-johansson-mr** [comment]
Oh, thanks!!! :-)

**Comment by mckaragoz** [comment]
6.4.9 is just released, please check it again with this release.

**Comment by jan-johansson-mr** [comment]
Yeah, works good now, thanks!!!
