### ISSUE TITLE
MudCSVMapper separator character parameter

### ISSUE THREAD

**Issue by EFIDEMMS** [CodeBeamOrg/CodeBeam.MudExtensions#190]
Adding a parameter to change the separator character. Right now it is comma, but, for example, in France, it has to be semi-colon.
The classic values for this kind of file are: comma, semi-colon & tab.

**Comment by mckaragoz** [comment]
@enkodellc could you look at this if you have time?

**Comment by enkodellc** [comment]
#195  should resolve this issue.

**Comment by mckaragoz** [comment]
@EFIDEMMS added Delimiter parameter to MudCsvMapper (thanks to enkodellc), will come with the next release.
