### ISSUE TITLE
MudPasswordField not show button switch text <-> masked

### ISSUE THREAD

**Issue by franklupo** [CodeBeamOrg/CodeBeam.MudExtensions#191]
The button for switch text <-> mask does not appear.

where am i wrong?

best regards

**Comment by mckaragoz** [comment]
It's a bug coming with the new releases. Easy fix, but will come in 1 week with new release. You can use older versions (< 6.4.9) for this week.

**Comment by mckaragoz** [comment]
6.4.11 is now released.
