### ISSUE TITLE
MudStepper click button step bypass validation

### ISSUE THREAD

**Issue by franklupo** [CodeBeamOrg/CodeBeam.MudExtensions#202]
Hi,
if you clickc button step the validation is bypassed.

![image](https://user-images.githubusercontent.com/6276309/235693050-fb584e1e-2a16-45b7-a967-5426c55ead1f.png)

Best regards

**Comment by franklupo** [comment]
News?

**Comment by mckaragoz** [comment]
Will fix probably with the next release
