### ISSUE TITLE
 MudListExtended - Multiple values doesn't show Initiallly when Virtualize

### ISSUE THREAD

**Issue by segfault-** [CodeBeamOrg/CodeBeam.MudExtensions#203]
MudListExtended, @bind-SelectedValues initially loading with 3 selected..... but only one selection is rendered..... if you use the scrollbar or type in the search filter then suddenly it renders correctly.  reproduced with :  https://try.mudblazor.com/snippet/cucxOyvMVJrhvQpK

**Comment by mckaragoz** [comment]
Yes, it look like we have a bug with ItemCollection approach. Initial values works with RenderFragment approach
https://try.mudblazor.com/snippet/wucRazYhLerRJsIq

**Comment by mckaragoz** [comment]
Update: It also works on ItemCollection, the problem is `Virtualize`

**Comment by segfault-** [comment]
Ill link a try

**Comment by mckaragoz** [comment]
This issue fixed with last release, thanks to @radderz again. We can close it now.
