### ISSUE TITLE
MudWatch initial Value for the StopWatch not working

### ISSUE THREAD

**Issue by Hiden46** [CodeBeamOrg/CodeBeam.MudExtensions#206]
I'm trying to set an initial value for the StopWatch function but it doesn't seem to work.
The value is passed as an initial parameter when configuring the component.

`<MudWatch @ref="watch" Mode="WatchMode.StopWatch" Value="@(new TimeSpan(1, 0, 0))"
                      Wheel="false" ShowHour="true" ShowMinute="true" ShowSecond="true" ShowMillisecond="false"
                      Typo="Typo.h6" />`

The value is displayed only after a `StateHasChanged()` but when I start the MudWatch then it doesn't update the time.

**Comment by mckaragoz** [comment]
Should be fixed with next release.

But have a reminder for the usage, `Value` is two-way binded so you need to use
```
@bind-Value="_value"`
_value = new TimeSpan(1, 0, 0);
```
 instead of `Value="@(new TimeSpan(1, 0, 0))"`
