### ISSUE TITLE
MudStepper vertical Timeline breaks after a certain height

### ISSUE THREAD

**Issue by jeffreyjsung** [CodeBeamOrg/CodeBeam.MudExtensions#207]
![Screenshot 2023-05-13 223727](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/44956373/1debf27d-8fac-47a9-91ee-535099d28266)
It would be nice if it could be longer.

**Comment by segfault-** [comment]
could you provide a try.mudblazor.com to reproduce?  use https://trymudextensions.pages.dev/  to reproduce, then go to https://try.mudblazor.com/ and copy paste / save / share link

**Comment by jeffreyjsung** [comment]
https://try.mudblazor.com/snippet/mawnOplLAFBqVzBl, notice the `Style="height:610px"` part of MudStepper. It starts misaligning after ~550px

**Comment by segfault-** [comment]
thanks for the feedback, i have submitted a PR to fix this issue

**Comment by mckaragoz** [comment]
This issue is fixed with the new release. Please re-open the issue if you will have a problem.
