### ISSUE TITLE
MudSelectExtended adornment shifts when values fill the selected values part

### ISSUE THREAD

**Issue by MatthijsVollenbroek** [CodeBeamOrg/CodeBeam.MudExtensions#222]
Hi there, 

I've noticed (also on your own documentation site) that selecting multiple values on the multiselect shifts the adornment outside of the input area, instead of stopping the text overflow earlier: 
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/46601320/95e66251-1896-40c0-8e3a-abea008507bd)

Maybe you already have a fix for this and otherwise I would like to make you aware of this issue (if you are not already)

Thanks in advance for helping out!

**Comment by mckaragoz** [comment]
Could you check it with the previous version? In last release we changed base input a bit

**Comment by MatthijsVollenbroek** [comment]
Thanks for the swift reply!

I just checked with version 6.4.13 and it works perfectly fine!
So I think you are correct that some change affected it.

As for now I am only using the package for datetime selector and this multi select feature. Would you recommend keeping it at version 6.4.13 for now? I have no idea how quickly these things are resolved, just started using this library today and I am very happy with the features this adds to the core mudblazor.

**Comment by mckaragoz** [comment]
> As for now I am only using the package for datetime selector and this multi select feature. Would you recommend keeping it at version 6.4.13 for now? I have no idea how quickly these things are resolved, just started using this library today and I am very happy with the features this adds to the core mudblazor.

If you still want to use MudSelectExtended its better to wait 6.5.1 and use 6.4.13 for now. But you can use MudComboBox with the latest release, probably it doesn't have the visual bugs.

**Comment by MatthijsVollenbroek** [comment]
As I do not see any combobox documentation on the website other than the API, I am not completely sure how that works. I will stick to this version for now and look forward to the next version!

**Comment by mckaragoz** [comment]
> As I do not see any combobox documentation on the website other than the API, I am not completely sure how that works. I will stick to this version for now and look forward to the next version!

It's there: https://codebeam-mudextensions.pages.dev/mudcombobox

**Comment by MatthijsVollenbroek** [comment]
Ah i didnt see it in the sidebar, this is actually even more useful to use for me! Then I will stick to the newest version. Thanks again!

**Comment by mckaragoz** [comment]
6.5.0.2 hotfix is released, thanks for the feedback.
