### ISSUE TITLE
New components: ToggleButton and RadioButtonGroup - Alternative to RadioGroup

### ISSUE THREAD

**Issue by danielchalmers** [CodeBeamOrg/CodeBeam.MudExtensions#232]
Also suggested on main repo: https://github.com/MudBlazor/MudBlazor/issues/7046

An alternative to `RadioGroup` that's styled as buttons:

```razor
<RadioButtonGroup @bind-SelectedOption="MyNullableBool">
	<ToggleButton Option="false" Color="Color.Primary">No</ToggleButton>
	<ToggleButton Option="true" Color="Color.Primary">Yes</ToggleButton>
</RadioButtonGroup>
```

![Animation](https://github.com/MudBlazor/MudBlazor/assets/7112040/137079c6-9e1b-4eeb-8204-627716149d6f)

Clicking a button will select that value, clicking again deselects it - Like the `ToggleIconButton` but with full text.

Similar to `RadioButtonGroup`:

```razor
<MudRadioGroup @bind-SelectedOption="MyNullableBool">
	<MudRadio Option="false" Color="Color.Primary">No</MudRadio>
	<MudRadio Option="true" Color="Color.Primary">Yes</MudRadio>
</MudRadioGroup>
```

### Have you seen this feature anywhere else?

- https://vuetifyjs.com/en/components/button-groups/
- https://mui.com/material-ui/react-toggle-button/

**Comment by mckaragoz** [comment]
I think we need this https://m3.material.io/components/segmented-buttons/overview

**Comment by segfault-** [comment]
i was just looking at the spec for this, agree this would be a welcomed addition

**Comment by mckaragoz** [comment]
Probably we add `MudToggleGroup` component into core library. Not only button specific component, a general single, toggle and multiselection component. That will be the ultimate solution about horizontal selections.

**Comment by danielchalmers** [comment]
Resolved by https://github.com/MudBlazor/MudBlazor/pull/7309
