### ISSUE TITLE
MultiSelection Autocomplete

### ISSUE THREAD

**Issue by Hobbs1210** [CodeBeamOrg/CodeBeam.MudExtensions#236]
Any timeline on when the Autocomplete extension described in this [MudBlazor PR ](https://github.com/MudBlazor/MudBlazor/pull/5150) will be added to this extension library ?

**Comment by mckaragoz** [comment]
Actually, its hard to add multiselection to autocomplete because it needs nearly complete redesign.

Instead of this, now the extension package has `MudComboBox`. The newest design that unites select and autocomplete features. If you need a feature, we can move with combobox.

**Comment by Hobbs1210** [comment]
> Actually, its hard to add multiselection to autocomplete because it needs nearly complete redesign.
> 
> Instead of this, now the extension package has `MudComboBox`. The newest design that unites select and autocomplete features. If you need a feature, we can move with combobox.

Thank you!! I will move forward with ComboBox

**Comment by Hobbs1210** [comment]
close

**Comment by pkuehnel** [comment]
Where can I find MudComboBox? I googled for it, but no results.

Just found it [Nuget Package](https://www.nuget.org/packages/CodeBeam.MudBlazor.Extensions/6.5.0.1) and
[CodeExamples](https://codebeam-mudextensions.pages.dev/mudcombobox)
