### ISSUE TITLE
MudSelectExtended - bind-Value doesn't show Initiallly when ItemCollection set bug

### ISSUE THREAD

**Issue by segfault-** [CodeBeamOrg/CodeBeam.MudExtensions#237]
see screenshot

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/10943569/c5969431-20db-4774-a1a8-10185323705c)

**Comment by mckaragoz** [comment]
Need more info, a basic string ItemCollection is working initially 🙂

**Comment by segfault-** [comment]
https://try.mudblazor.com/snippet/GOQnOgnaqbMLLJkV

**Comment by mckaragoz** [comment]
This example is fixed by #239 we can close this issue.
