### ISSUE TITLE
MudStepper SetActiveStepByIndex Issue

### ISSUE THREAD

**Issue by quinzyCLC** [CodeBeamOrg/CodeBeam.MudExtensions#242]
Hi

I seem to have an issue with the MudStepper. 

I have a function that allows me to move the Stepper forwards based on conditions. This function contains the SetActiveStepByIndex function. This only works if I click the button twice. It's as if the stepper does not respond the first time.

The same happens in my OnAfterRenderAsync Method. When the page is done loading I have to click somewhere on the stepper for it to actually jump to the set step. 

I have also been keeping my versions up to date. So I doubt it's that.

Here is the OnAfterRenderAsync method i am using:

`protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        if (!firstRender)
        {
            await _stepper.SetActiveStepByIndex(_StepperIndex, false, true);
            if (!_CaseRejected && _StepperIndex == 0)
            {
                _MudWatch.Start();
            }
        }
    }`

Here is an example of my button onclick function:

`
 private async void AcceptCase()
    {
        var acceptResult = await SomeService();
        if (acceptResult.Success)
        {
            _MudWatch.Stop();
            await _stepper.SetActiveStepByIndex(1);
            Snackbar.Add("Case has been accepted", Severity.Info);
            NavigationManager.NavigateTo("/Cases/View/Single/" + CaseId + "/" + UserId, true);
        }
        else
        {
            Snackbar.Add("Some Errors Occured", Severity.Error);
            NavigationManager.NavigateTo("/");
        }
    }
`

**Comment by mckaragoz** [comment]
Can you provide more info or try example? (you can prepare example on https://trymudextensions.pages.dev/ and copy the code)

On first glance, i thought you should not do it in OnAfterRender. Did you try to set step in OnParametersSet?

**Comment by quinzyCLC** [comment]
Hi

Thank you. Ill prepare an example for you shortly. 

Can you provide me with a suggested way in the meantime of how I would be able to set the active index on page load.

**Comment by dom3d** [comment]
I have the same issue. Calling "_stepper.SetActiveStepByIndex(1);" in a button callback method. First time it goes to index 0 and only the second time it goes to index 1.

**Comment by mckaragoz** [comment]
@quinzyCLC you need to call `StateHasChanged`. And it should be async. Like:

```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await _stepper.SetActiveStepByIndex(1);
            StateHasChanged();
        }
    }
```

**Comment by mckaragoz** [comment]
> I have the same issue. Calling "_stepper.SetActiveStepByIndex(1);" in a button callback method. First time it goes to index 0 and only the second time it goes to index 1.

Tried an example and it is working for me. Do you have an example?

**Comment by quinzyCLC** [comment]
> @quinzyCLC you need to call `StateHasChanged`. And it should be async. Like:
> 
> ```
> protected override async Task OnAfterRenderAsync(bool firstRender)
>     {
>         if (firstRender)
>         {
>             await _stepper.SetActiveStepByIndex(1);
>             StateHasChanged();
>         }
>     }
> ```

This works for me with a change

* I had to change the if(firstRender){} to if(!firstRender && renderCount < 2) otherwise the _stepper doesn't exist. 
But otherwise, it seems fine. 

Using StateHasChanged(); on onclicks works for me too.

Thank you for the assistance.
