### ISSUE TITLE
MudSwitchM3 style is broken when typeparam is bool?

### ISSUE THREAD

**Issue by marcoatribeiro** [CodeBeamOrg/CodeBeam.MudExtensions#254]
When MudSwitchM3 is created with `T="bool?"`, the toggle button color is not set correctly, as the class `mud-switch-thumb-...-m3` is not set in the `span` element.

The issue seems to be in the below line in **MudSwitchM3.razor** file.

```html
<span class="mud-switch-thumb-m3 @(BoolValue == false ? $"mud-switch-thumb-{Color.ToDescriptionString()}-m3" : null) @(string.IsNullOrEmpty(ThumbOffIcon) ? null : "mud-switch-thumb-off-icon-m3") d-flex align-center justify-center">
```

**Comment by mckaragoz** [comment]
I think switch component should not support tristate. It's a checkbox feature. It has two different values to switch between them.

**Comment by marcoatribeiro** [comment]
Actually the idea is not exactly supporting tristate, but often we have entity properties which can be null and they, in turn, have bool properties, which would make the resulting property a nullable boolean. E.g. `Vehicle?.IsCar` (IsCar is bool but the result of this check is a bool?).

Besides that, MudSwitch does support a typeparam and I understand the idea is to make MudSwitchM3 100% compatible with it, or am I wrong?

https://github.com/MudBlazor/MudBlazor/blob/db831e6867d9ebe396ee21a7755292378270814b/src/MudBlazor/Components/Switch/MudSwitch.razor#L3C1-L3C13

**Comment by mckaragoz** [comment]
Yes its generic. The original MudSwitch is also generic. It supports to switch between two string or int values.

Do you have any idea how switch should look when its on third state?

**Comment by marcoatribeiro** [comment]
I just performed a test and it seems that, for MudSwitch, both `null` and `false` states have the same look.

https://try.mudblazor.com/snippet/cOmdErmDINbILUik

**Comment by mckaragoz** [comment]
Thanks for the idea. With new release, `null` and `false` states looks same.
