### ISSUE TITLE
MudCodeInput error

### ISSUE THREAD

**Issue by ivanjx** [CodeBeamOrg/CodeBeam.MudExtensions#258]
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/12814796/ac6a2fb9-2450-4e9f-b956-67a23f97e703)

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/12814796/c4649a9c-9fa9-4c49-a5b0-9844b204b7a5)

`Otp` is a string property in the code behind with value `""`.

**Comment by mckaragoz** [comment]
I need more info about the error, at which point this error occurs, on initialization or pressing some keys?

**Comment by ivanjx** [comment]
on initialization. i realized that Otp must be null and not empty to avoid this.

also the Error and ErrorText properties does not seem to work.

**Comment by mckaragoz** [comment]
Added Error and ErrorText. Fix a lot with #402. Please check it after next release and report if there any issues.
