### ISSUE TITLE
MudComboBox Select All Filtered

### ISSUE THREAD

**Issue by PlayerModu** [CodeBeamOrg/CodeBeam.MudExtensions#262]
Does the MudComboBox component currently support the ability to "Select All" but only selecting all from the whole list that I've filtered?

I.e I have a list of 10 items, I've filtered those items by A, so there are 5 in the selectable dropdown. If I click "Select All", will it select the entire 10 items or just the filtered 5?

**Comment by mckaragoz** [comment]
It look like currently select all not related to what we filter. Do you have an offer?

**Comment by PlayerModu** [comment]
I don't have any code to offer for a PR at the moment. But maybe design wise, it could work in a similar way to Select All. I.e you set a new property to true, and if so another checkbox appears beneath Select All like "Select All Filtered" which then only selects the ones currently in the dropdown list? If you then changed the filter it would show only those as selected until you re-clicked it and it changes the selected to the newest filtered list?

**Comment by PlayerModu** [comment]
Thank you for providing a solution to this issue. I'll feedback any further issues identified.
