### ISSUE TITLE
MudStepper action buttons on top?

### ISSUE THREAD

**Issue by RING-mbrown** [CodeBeamOrg/CodeBeam.MudExtensions#263]
Is there a way to change the styling of the MudStepper action buttons so they are oriented at the top of the component just below the header?

**Comment by mckaragoz** [comment]
I think there is no direct solution about that. But you can create your own `StaticContent` at the top and remove all action buttons.

**Comment by RING-mbrown** [comment]
> I think there is no direct solution about that. But you can create your own `StaticContent` at the top and remove all action buttons.

Thank you. As soon as I'd posted it, had a cup of coffee, I realized I could create my own buttons that interact with the Stepper component. Works like a charm, thank you very much for your reply.
