### ISSUE TITLE
Setting the border radius on the MudBarcode component

### ISSUE THREAD

**Issue by JunaidSultan20** [CodeBeamOrg/CodeBeam.MudExtensions#278]
# Prerequisites
I am working with Blazor application and have implemented *MudBarcode* component to generate the QR code on the UI. I need to apply specific border radius on the bar code. I tried by adding it through the style property and setting important attribute to it as well but it didn't worked. How can we apply the border-radius: 25px for the QR Code. 

# Expected Behavior

- When I set the *border-radius: 25px !important;* the QR Code should have rounded corners.

# Current Behavior

- The QR Code appears with squared borders.

## Steps to Reproduce

1. Set border radius by setting the Style property *Style="border-radius: 25px !important;"* 

## Context
* Operating System: Windows 10
* Browser: Microsoft Edge

**Comment by mckaragoz** [comment]
Added Class and Style parameters in SVG. Will release with next version.
