### ISSUE TITLE
[Bug][[MudRangeSlider] When Min value is set to value other than 0 the visible range misbehaves

### ISSUE THREAD

**Issue by Drutol** [CodeBeamOrg/CodeBeam.MudExtensions#289]
Hello, thanks for the great package! Was playing today with MudRangeSlider and noticed a bug whenever I set the `Min` value to something other than `0`. The inner part between the points should be coloured and the tooltip appearing above the slider "knob" should be above it. Looks like it gets offset wrongly in some way. Everything works when the `Min` is set to `0` Thanks!

Pics from the sample page for version v6.6.0:
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/6102530/0b02a224-4849-44be-b0b8-e3cb54b67100)
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/6102530/85a2e038-200f-47ff-9f51-89b7dbd176f8)

**Comment by mckaragoz** [comment]
@enkodellc what do you think? It's broken when we set MinValue more than 0.

**Comment by enkodellc** [comment]
I have a local fix for this but haven't had the time to push a fix to the repo.

**Comment by mckaragoz** [comment]
Fixed with #347.
