### ISSUE TITLE
[Bug] MudSelectExtended - When using tab key in search box the component is throwing exception.

### ISSUE THREAD

**Issue by sovensblackhawk** [CodeBeamOrg/CodeBeam.MudExtensions#290]
Using tab key from the search box below
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/77590440/dcf27561-7371-4407-bd55-144082e03fe4)

Error in console log

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/77590440/d1c92336-5843-416e-af08-3a47fcac57d7)

**Comment by mckaragoz** [comment]
Did you add script described at installation section in Readme?

**Comment by sovensblackhawk** [comment]
Ah sorry, my bad. A colleague of mine integrated this into our projects so I assumed it was added throughout our web projects correctly. Thanks for the response.
