### ISSUE TITLE
MudSelectExtended - Select All Not working on Virtualize

### ISSUE THREAD

**Issue by nandhakumar92** [CodeBeamOrg/CodeBeam.MudExtensions#296]
Use Case: Virtualize=true and MultiSelect=true

When clicking Select All. Only the Scanned Items are getting Selected

**Comment by PlayerModu** [comment]
I'm not sure what you mean by "scanned" items sorry. The Select All behaviour was changed in the latest version of this library to only select all of the items currently shown in the dropdown list, not all the items from the whole list. 

This means if you have a list of ten items, and you filter them down to only 5, select all will select only those 5. But if you don't filter them down the original ten will be selected as they're in the dropdown.

Hope that helps? If not I'll leave it up to the library maintainers to help :)

**Comment by nandhakumar92** [comment]
Hi @PlayerModu ,

It's not with the filter. The issue occurs when Virtualize= true. For instance, in the ItemCollection I have 100 items. With Virtualize enabled only a few sets of items (i.e. 20 items) will be rendered initially. With the Select ALL being clicked. Only the rendered 20 items get selected instead of the entire 100.

Hope this clarifies.

**Comment by PlayerModu** [comment]
I understand ☺️ Sorry if I caused any confusion, hopefully this issue can be looked at and resolved asap!
