### ISSUE TITLE
ComboxBox: Multiselection+Editable+Filter = Mouse click clears searchbox

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#306]
[MudExtensions Example: Basics & Visual](https://codebeam-mudextensions.pages.dev/mudcombobox)

After typing `co` and clicking on 1 of the items from the list, the searchbox is cleared which I do not expect.
When I use the keyboard to make a selection (arrow keys + enter), the searchbox does not get cleared, as expected.

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/10358198/d2871913-e54a-4b17-9362-c5696ef42f64)

**Comment by Yomodo** [comment]
It does seem to work in the next example. The bug surfaces when `Strict` is enabled.

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/10358198/4829ec8b-4a07-4ee4-9248-0e58e89c4904)

**Comment by mckaragoz** [comment]
It only occurs on first selection. If selectedvalues already has a value, it works without problem.
