### ISSUE TITLE
Deprecated NuGet / Project?

### ISSUE THREAD

**Issue by jonaswikstrom** [CodeBeamOrg/CodeBeam.MudExtensions#336]
If all your NuGet versions are deprecated, users may only realize it when attempting to download the component as a NuGet package. Consider adding notices on your website or GitHub for clear communication, saving users from unnecessary frustration and time.

Is this a sign that the project is no longer actively maintained? If so, it might be worth asking on GitHub if someone is interested in taking over. With a substantial and well-functioning codebase, there could be developers willing to continue the project's development and support.

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/16499417/44488809-0e50-4d46-ade5-8bd5294fee13)

**Comment by mckaragoz** [comment]
Hi, we moved the library to a new namespace long time ago. 6.4.0 and after releases have new package. Deprecated packages have the info of the new Nuget packages. The old package has worse search results when users search what MudBlazor has. 

This library will maintain while Blazor and MudBlazor live.
