### ISSUE TITLE
Add BlazorSliders to  MudBlazor Extension?

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#34]
I think this would be an awesome MudBlazor Extension addition: [blazorslidertest](https://blazorslidertest.azurewebsites.net/)

Original: https://github.com/carlfranklin/BlazorSliders/

**Comment by mckaragoz** [comment]
If im not wrong it heavily using js right? And it doesn't work for mobile (touch events).

**Comment by mckaragoz** [comment]
Good news. We added `MudSplitter` with #38. It has unique design, has no javascript. Only downside is it doesn't have horizontal support yet.

**Comment by Yomodo** [comment]
You have made my day, Thank you!
