### ISSUE TITLE
MudSelectExtended doesn't allow a space in the search function

### ISSUE THREAD

**Issue by enkodellc** [CodeBeamOrg/CodeBeam.MudExtensions#345]
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/2935721/b723c7cb-c70c-41d5-be47-469e6f3a686e)

If I try to search for a value that has a space in it, it will not allow you to add that space, in the demo try typing in American Samoa, it will not allow you to use the space bar.  It appears to work on 6.6.3 but not on 6.7 or 6.8. .
 
Sorry I do not have time to debug and submit a PR at this time.

**Comment by sfmskywalker** [comment]
I can confirm the issue exists in 6.9.0 as well.
When reverting to 6.6.3, it works.

**Comment by zackasattackas** [comment]
Found a [workaround](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/issues/137#issue-1598756770): Alt + 32

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/20526666/796cb2b3-feb0-44fe-b690-1d6262cca4f9)

**Comment by mckaragoz** [comment]
It should be fixed with 6.9.1
