### ISSUE TITLE
[MudListExtended] How to implement indeterminate state?

### ISSUE THREAD

**Issue by Arsync** [CodeBeamOrg/CodeBeam.MudExtensions#352]
MudCheckbox has indeterminate state. In some cases MudList must have that state with "half-selected items". As for example, popup of adding videos to Youtube playlists - if any of selected videos has been added previously to playlist B, playlist B becomes indeterminate state for other videos selected.

![2024-02-01_23-12-19](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/41461678/666440c5-f6f5-42af-95d3-797bc865af55)

**Comment by mckaragoz** [comment]
Does list item have sub items? If no you can add your own icon.

**Comment by Arsync** [comment]
As the workaround, it can be just a set of MudCheckBox items in foreach instead of MudList. Seems, to implement that on MudList, there must be Selected property on MudListItem with two-way binding to data item property `Selected` (nullable).
