### ISSUE TITLE
MudComboBox breaks the page layout

### ISSUE THREAD

**Issue by Saracaen** [CodeBeamOrg/CodeBeam.MudExtensions#354]
Opening the MudComboBox breaks the page layout and removes any scrollbars, if present. You can see an example of this one the documentation page for the MudComboBox. Notice how opening any of the combo box components will remove the scrollbar on the right hand side.

https://codebeam-mudextensions.pages.dev/mudcombobox

**Comment by mckaragoz** [comment]
MudComboBox has `LockScroll` parameter to choose remove scrollbar or not. The default is true.

**Comment by Saracaen** [comment]
That fixes it indeed, thanks!
