### ISSUE TITLE
MudComboBox SelectAll layout issues

### ISSUE THREAD

**Issue by Saracaen** [CodeBeamOrg/CodeBeam.MudExtensions#355]
The MudComboBox supports the SelectAll property, which adds a select all checkbox at the top of a multi-select list. But the select all checkbox is not properly aligned with the rest of the checkboxes.

![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/72379653/ed65c4af-5d7a-4b35-9191-4541767efedb)

The MudComboBox is defined as follows:

```
<MudComboBox T="string"
           SelectedValues="_SelectedCables"
           SelectedValuesChanged="OnSelectedCablesChangeAsync"
           SelectAll="true"
           MultiSelection="true"
           Label="@Localizer["SelectCable"]"
           Placeholder="@Localizer["Select a cable..."]"
           AnchorOrigin="Origin.BottomCenter"
           Dense="Dense.Slim"
           Margin="Margin.Dense"
           Variant="Variant.Outlined">
    @foreach ( var cable in _CableNames )
    {
        <MudComboBoxItem Value="@cable.CableName">@cable.CableName</MudComboBoxItem>
    }
</MudComboBox>
```

**Comment by mckaragoz** [comment]
Which version do you use?

**Comment by Saracaen** [comment]
This was an issue for me in version 6.9.0, but it is no longer an issue since 6.9.1!
