### ISSUE TITLE
MudBarCode rendering UPC_A and UPC_E incorrectly

### ISSUE THREAD

**Issue by kencherasaro** [CodeBeamOrg/CodeBeam.MudExtensions#357]
It appears that the inner <rect> tags for these SVGs are rendering with a height of 1 when the value should be larger.  Thinking it could be a parameter or possibly calculated.

`<rect class="d-flex align-center justify-center" width="1" height="1" style="fill: black; stroke-width: 0px; stroke: black;" x="9"y="0">`

<img width="1267" alt="Screenshot 2024-03-06 at 8 12 41 AM" src="https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/3354398/26243964-8b04-4e7d-9cec-bd5ed5e41063">

https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/blob/1c05d6cf7b95c7c0d10e12ec01755756f0841199/CodeBeam.MudBlazor.Extensions/Components/Barcode/MudBarcode.razor#L20

https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/blob/1c05d6cf7b95c7c0d10e12ec01755756f0841199/CodeBeam.MudBlazor.Extensions/Components/Barcode/MudBarcode.razor.cs#L62

https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/blob/1c05d6cf7b95c7c0d10e12ec01755756f0841199/CodeBeam.MudBlazor.Extensions/Components/Barcode/BarcodeResult.cs#L14

**Comment by mckaragoz** [comment]
Im not have expertise on this component. You can prepare a PR. Is it only about making it as a parameter?

**Comment by mckaragoz** [comment]
Added `ForceHeight` parameter, you can use it on rectangle shaped barcode formats. Will come with next release.
