### ISSUE TITLE
ShrinkLabel for MudBaseInput

### ISSUE THREAD

**Issue by MilesFan** [CodeBeamOrg/CodeBeam.MudExtensions#363]
The new feature ShrinkLabel of MudBlazor MudBaseInput can be useful, can CodeBeam.MudBlazor.Extensions inherit it?

**Comment by mckaragoz** [comment]
Isn't is same as `ForceShrink`?

**Comment by MilesFan** [comment]
Sorry I must have overlooked, closing this issue.
