### ISSUE TITLE
MudStepper - No way to Uncomplete a step

### ISSUE THREAD

**Issue by adversive** [CodeBeamOrg/CodeBeam.MudExtensions#364]
I'm sure that I'm missing something here, but I can't see any way to uncomplete a step after calling CompleteStep(stepIndex).

When going back in steps, I want to uncomplete all steps that come after.

**Comment by mckaragoz** [comment]
There is a `Reset` method in MudStepper to set all step status to continued. With the latest release 6.9.2 we also added `SetStepStatus` method that now you can set step status with step index programmatically.

**Comment by adversive** [comment]
Thanks, using `SetStepStatus` is sufficient.
