### ISSUE TITLE
MudStepper "ProgressValue" not updating when adding/removing steps

### ISSUE THREAD

**Issue by SKSniperSK** [CodeBeamOrg/CodeBeam.MudExtensions#386]
Hi,

when you have already passed the first step and then are dynamically adding/showing or removing/hiding a (new) step, the according progress indicator bar is not being updated. This is because the (internal) value "ProgressValue" is only re-calculated once the (also internal) property "ActiveIndex" gets changed, which is not the case with AddStep/RemoveStep.

Example:
 - you have 4 steps and start on step 1 of 4 with ActiveIndex=0 and ProgressValue=0
 - you proceed to step 3 of 4 with ActiveIndex=2 and ProgressValue=66%
 - you show/add a new step and are now on step 3 of 5 with ActiveIndex=2 (which is still correct and has not changed) and ProgressValue=66% (which is wrong as it should be 50% now)
(the same applies if you remove/hide a step)

Solution:
ProgressValue has to be re-calculated every time the number of steps changes (AddStep/RemoveStep)
Perhaps it would also be a good idea to have some accessible way to trigger an update, either by making ProgressValue itself accessible or adding an accessible update method.

Thanks!

**Comment by mckaragoz** [comment]
Fixed and will come with next release. Adding or removing steps automatically updates ProgressValue. You can also call `ForceRender` to update ProgressValue manually too.
