### ISSUE TITLE
MudListExtended: pressing Ctrl+A in Searchbox selects all list items instead of highlighting text

### ISSUE THREAD

**Issue by MartinSoka** [CodeBeamOrg/CodeBeam.MudExtensions#409]
I have a MudListExtended with SearchBox and MultiSelection=true.
When filtering the list using Searchbox and pressing Ctrl+A to highlight the text all list items are selected.

Expected behavior: This should select the search text as the list is not in focus.

**Comment by mckaragoz** [comment]
Did it complete? I can look at if issue still exits.

**Comment by MartinSoka** [comment]
sry i closed it, it was my fault, because i had a custom searchbox implementation due to the issues with RenderFragment & Searchbox.
