### ISSUE TITLE
MudFileUpload triggered twice with MudLoadingButton

### ISSUE THREAD

**Issue by SpicyBoyd** [CodeBeamOrg/CodeBeam.MudExtensions#413]
### Bug type

Component

### Component name

MudLoadingButton

### What happened?

MudFileUpload triggered twice with MudLoadingButton

### Expected behavior

MudFileUpload triggered once with MudLoadingButton

### Reproduction steps

```C#
<MudFileUpload T="IBrowserFile" FilesChanged="UploadFiles">
    <ActivatorContent>
        <MudLoadingButton Loading="UploadLoading" 
                   Variant="Variant.Filled"
                   Color="Color.Primary"
                   StartIcon="@Icons.Material.Filled.CloudUpload">
            Upload Files
        </MudLoadingButton>
    </ActivatorContent>
</MudFileUpload>
```

- https://github.com/MudBlazor/MudBlazor/issues/9072

### Version (bug)

7.0.0-preview.4

### What browsers are you seeing the problem on?

Chrome

### On which operating systems are you experiencing the issue?

Windows

**Comment by nvnd295** [comment]
I managed to fix it like this:

`<MudButton HtmlTag="label"
           Variant="Variant.Filled"
           Color="Color.Primary"
           StartIcon="@Icons.Material.Filled.CloudUpload">
    Upload Files
    <MudFileUpload T="IBrowserFile"
                   Accept=".xlsx"
                   FilesChanged="UploadFile"
                   MaximumFileCount="1">
    </MudFileUpload>
</MudButton>`

so without the activator content and putting the fileupload inside the button. Don't know if it's the way to go though :)
