### ISSUE TITLE
MudListExtended error

### ISSUE THREAD

**Issue by TasosSarris** [CodeBeamOrg/CodeBeam.MudExtensions#424]
Hi
Please note this error: Cannot provide a value for property 'ScrollManagerExtended' on type 'MudExtensions.MudListExtended
after the use of MudBlazor 7.0 with CodeBeam rc1

**Comment by TasosSarris** [comment]
Please ignore it, it was because of missing the builder.Services.AddMudExtensions() to the program.cs

**Comment by mckaragoz** [comment]
Thanks for your answer, we can close it.
