### ISSUE TITLE
(Suggestion) Add property to disable backspace chip deletion in ChipField

### ISSUE THREAD

**Issue by russkyc** [CodeBeamOrg/CodeBeam.MudExtensions#440]
Currently if I press backspace continuously when the ChipField input is empty I am delete all previously typed chips. For avoiding user error, it would be useful to have a property that disables this behavior and allowing only removal when the user presses remove on the chip. Maybe something like `BackspaceChipRemoval="false"` which will be on by default to keep the existing behavior.

**Comment by mckaragoz** [comment]
Makes sense, added `BackspaceChipRemoval` parameter to the component. Will release on 7.0.1
