### ISSUE TITLE
Small bug in the combobox

### ISSUE THREAD

**Issue by IngoManthey** [CodeBeamOrg/CodeBeam.MudExtensions#447]
The MudForm is disabled, all MudComponents are readonly and the label is a different color. Your component is not ReadOnly. If I set the ReadOnly directly, only the color does not match.

![Combobox](https://github.com/user-attachments/assets/fd73b02a-2839-4e70-8037-db0d41d981a6)

**Comment by danielchalmers** [comment]
Could you post a [Try](https://trymudextensions.pages.dev/snippet) link? I'm not sure if I'm seeing the same thing

**Comment by IngoManthey** [comment]
@danielchalmers 
Here is a small example

<MudForm Model="@Model" Disabled="@FormIsDisabled">
   <MudGrid Spacing="2">
        <MudItem xs="12" md="6">
            <MudTextField Label="FullName" Variant="Variant.Filled" Required="true" />
        </MudItem>
         <MudItem xs="12" md="6">
            <MudComboBox Label="Role" Variant="TipMudConstants.EditorVariant" ReadOnly="TestReadOnly"
                         For="@(() => Model.Role)" Immediate="true" Required="true" >
                    <MudComboBoxItem Value="Admin" Text="@Admin"></MudComboBoxItem>
            </MudComboBox>
        </MudItem>
   </MudGrid>
</MudForm

@code 
{ 
    private bool FormIsDisabled = true;
    private bool TestReadOnly = true;

}

**Comment by danielchalmers** [comment]
@IngoManthey I think your comment example is broken?

**Comment by IngoManthey** [comment]
I have no time. sorry I use MudSelect.
