### ISSUE TITLE
404 on the the JS and CSS files

### ISSUE THREAD

**Issue by americanslon** [CodeBeamOrg/CodeBeam.MudExtensions#474]
![image](https://github.com/user-attachments/assets/7620a71d-15ca-4c67-a109-4cd261c7f9f8)

Added both to index.html 

![image](https://github.com/user-attachments/assets/53487b4d-22a4-4b1e-b42c-12073bbce0fe)

and added `AddMufExtenstions`

![image](https://github.com/user-attachments/assets/80b2e74e-0c4d-4a0a-a287-9399afd1582a)

I tried both v6.2.7 as well as v7.0.1

Considering how simple installation instructions are I am kind of flabbergasted - what could it be?

**Comment by mckaragoz** [comment]
Did you try cache refresh with Ctrl + F5?

**Comment by americanslon** [comment]
I did. Cleaned cached, tried different browsers even, restarted the PC. It's very odd. Installed/uninstalled package.

**Comment by americanslon** [comment]
It looks like I installed  `CodeBeam.MudExtensions` and not `CodeBeam.MudBlazor.Extensions`

Leaving this here for the next dumb dumb like myself but you might want to call it out on the install page - packages are easy to confuse, have an identical looking dev page, etc.

**Comment by mckaragoz** [comment]
Wow you are the first that wrote here :) It was very old, it's awesome that you can find
