### ISSUE TITLE
Would it be possible to split the extensions into more libraries to avoid depedencies from components you dont use?

### ISSUE THREAD

**Issue by JimWolff** [CodeBeamOrg/CodeBeam.MudExtensions#478]
I'd like to use many of the components in CodeBeam.MudBlazor.Extensions but i'd like to avoid depedencies in libraries like ZXing.Net or CsvHelper although those libraries are good, i dont want to depend on them unnessesarily, especially when making a webassembly app that has to have the smallest possible download footprint.

Maybe we could introduce a .Core lib and then move the things with dependencies in large projects into their own lilbrary and namespace?

**Comment by ScarletKuro** [comment]
> webassembly app that has to have the smallest possible download footprint

But WASM has trimming enabled by default. When you publish code, all code that is not used are removed.
Good example of it is MudBlazor, full size is 8mb, but on my app it reduces to 450kb.

Alternative, you could add some libraries to `BlazorWebAssemblyLazyLoad` but never actually load them.

**Comment by JimWolff** [comment]
Thank you for the answer, that's interesting, the times I've tried trimming apps i had to turn it on manually.

Since many web applications call external things through httpclients using json de-/serialization of objects which people mostly use in the "reflection way" instead of the source generated way, I assumed you couldnt use trimming before moving away from things that use refelction, otherwise the trimmer might just remove things that it shouldnt.

I'll try looking a bit more at what it's actually publishing and maybe different trimming settings. The `BlazorWebAssemblyLazyLoad` is also a good point that i might use regardless.

**Comment by ScarletKuro** [comment]
> Thank you for the answer, that's interesting, the times I've tried trimming apps i had to turn it on manually.

Before .net8 you had to manually set the `<PublishTrimmed>true</PublishTrimmed>`. Now it shouldn't be necessary.

> instead of the source generated way

I would strongly advice to use sourcegen if you are using WASM. Not only for the speed but it's also trimming safe.

**Comment by JimWolff** [comment]
Thanks exactly what I'm doing both with JsonSerializerContext but also logging and other things that have source gen functionality.
