### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by GioviQ** [CodeBeamOrg/CodeBeam.MudExtensions#48]
https://mudextensions.azurewebsites.net/api

Error 403 - This web app is stopped.

**Comment by mckaragoz** [comment]
Yes we changed the URL, for now i choose free hosting options. If you see somewhere the old URL still remains, please inform us.

**Comment by GioviQ** [comment]
only in README

**Comment by mckaragoz** [comment]
It fixed now, thanks.
