### ISSUE TITLE
Update package to support MudBlazor v8

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#481]
Hi,

Would it be possible to release an update that supports the current MudBlazor v8 preview?

**Comment by ScarletKuro** [comment]
@mckaragoz

**Comment by mckaragoz** [comment]
Version 8.0.0-preview.1 released :)

**Comment by Yomodo** [comment]
> Version 8.0.0-preview.1 released :)

Thanks!
