### ISSUE TITLE
error: Cannot provide a value for property 'ScrollManagerExtended' when using a ComboBox

### ISSUE THREAD

**Issue by notAnElephant** [CodeBeamOrg/CodeBeam.MudExtensions#487]
I tried to add a ComboBox to my application, but it failed to load, and it threw the exception in the title. I did not intend to use any kind of scrollmanager though. 

I literally just copied the combobox's code from the documentations: 

https://mudextensions.codebeam.org/mudcombobox#basics--visual

Please, help me out! :)

**Comment by mckaragoz** [comment]
It look like you didn't install package properly. Please read Readme file and add js and css content to your application first. The installation process is the same as MudBlazor core, you should be familiar

**Comment by notAnElephant** [comment]
thanks, it seems like it resolved the issues
