### ISSUE TITLE
MudBlazor CssBuilder Extension Methods

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#57]
In MudBlazor [issue](https://github.com/MudBlazor/MudBlazor/issues/5683): "MudTabPanel text is always capitalized" I posted a css fix for this.

I've seen many "tiny css" fixes and it could be convenient to encapsulate the css as extension methods.
For example:

```csharp
<MudTabPanel @ref="_tabPanel" ...
...

_tabPanel.NormalizeTabPanelText();
```
This would apply the approriate css using the MudBlazor CssBuilder methods.

**Comment by mckaragoz** [comment]
Sorry doesn't understand what do you offer.

**Comment by Yomodo** [comment]
Yeah, gonna close this one. Was a spur of the moment thing.
