### ISSUE TITLE
Splitter: Setting to Disabled doesn't set the splitter's cursor state

### ISSUE THREAD

**Issue by Yomodo** [CodeBeamOrg/CodeBeam.MudExtensions#85]
Whe the splitter is set to Disabled, the cursor's state remains `ew-resize` instead of something like `default`.

I've tried changing this in `MudSplitter.razor`, but that doesn't work.

```csharp
<MudSlider Style="@($"overflow: hidden; z-index: 6; cursor:{(DisableSlide ? "default !important" : "ew-resize !important")}")" ...
```

**Comment by mckaragoz** [comment]
Yeah this is a bug.

And for another issue, after last changes, i think you don't need to `overflow: hidden`, i added it in the library.
