### ISSUE TITLE
Scrollbar: doesn't work with MudDataGrid

### ISSUE THREAD

**Issue by gle4711** [CodeBeamOrg/CodeBeam.MudExtensions#86]
Hello, 

I am trying to apply the scrollbar extension to a MudDatagrid. If I leave out the selector it works. But I only want to change the scrollbar of the datagrid and not the scrollbars of all controls. Here is a sample:

https://try.mudblazor.com/snippet/QammlcQzwLXwMdZy

**Comment by gle4711** [comment]
I do not need this feature anymore.

**Comment by mckaragoz** [comment]
Actually didn't look at it deeply, probably need to arrange some CSS selectors.
